/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.log_in to edit this template
 */
package LogIN_SWI;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author Orestis
 */
public class log_in extends javax.swing.JFrame {

    /**
     * Creates new form java
     */
    public log_in() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Field_Username = new javax.swing.JTextField();
        Field_Password = new javax.swing.JPasswordField();
        jButton_cancel_exit = new javax.swing.JButton();
        BTN_Reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.focusedBorderColor"));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Username");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Password");

        Field_Username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Field_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_UsernameActionPerformed(evt);
            }
        });

        Field_Password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Field_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_PasswordActionPerformed(evt);
            }
        });

        jButton_cancel_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_cancel_exit.setText("Enter");
        jButton_cancel_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancel_exitActionPerformed(evt);
            }
        });

        BTN_Reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTN_Reset.setText("Reset");
        BTN_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Field_Password)
                            .addComponent(Field_Username)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_cancel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(BTN_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Field_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Field_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_cancel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Field_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_PasswordActionPerformed
        Field_Username.setText("");
        Field_Password.setText("");
    }//GEN-LAST:event_Field_PasswordActionPerformed

    private void jButton_cancel_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancel_exitActionPerformed
        Connection connection;
        String DB_URL = "jdbc:mysql://localhost:3306/travel_agency?useSSL = false";
        String USERNAME = "root";
        String PASSWORD = "123456789987654321";
        
        try{
            connection = DriverManager.getConnection(DB_URL, USERNAME, PASSWORD);
            
            String Username = Field_Username.getText();
            String Password = String.copyValueOf(Field_Password.getPassword());
            
            PreparedStatement st = (PreparedStatement)connection.prepareStatement("Select it_at, it_password from it_admin where it_at=? and it_password=?");
             st.setString(1, Username);
             st.setString(2, Password);
            ResultSet rs = st.executeQuery();
            if(rs.next())
            {
                dispose();
                Home_Page hpage= new Home_Page();
                hpage.show();
            }else{
                
                JOptionPane.showMessageDialog(this, "Username or Password Wrong..");
                Field_Username.setText("");
                Field_Password.setText("");
            }
            
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton_cancel_exitActionPerformed

    private void Field_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_UsernameActionPerformed

    private void BTN_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ResetActionPerformed
    
    }//GEN-LAST:event_BTN_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            log_in.util.logging.Logger.getLogger(log_in.class.getName()).log(log_in.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            log_in.util.logging.Logger.getLogger(log_in.class.getName()).log(log_in.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            log_in.util.logging.Logger.getLogger(log_in.class.getName()).log(log_in.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            log_in.util.logging.Logger.getLogger(log_in.class.getName()).log(log_in.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        log_in.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new log_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Reset;
    private javax.swing.JPasswordField Field_Password;
    private javax.swing.JTextField Field_Username;
    private javax.swing.JButton jButton_cancel_exit;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
